# main
# githubåœ°å€  https://github.com/6Svip120apk69
# TGé¢‘é“åœ°å€  https://t.me/mainscript
# TGäº¤æµç¾¤    https://t.me/joinchat/maming0001outlookAAE7XHm-q1-7Np-tF3g
# boxjsé“¾æ¥   https://raw.githubusercontent.com/6Svip120apk69/gitee_q8qsTAUA_cThxc1RBVUE/main/Task/main.boxjs.json



# âš ï¸âš ï¸âš ï¸ç‰¹åˆ«é‡è¦,åŠ¡å¿…è¿›è¡Œæ›¿æ¢æ“ä½œï¼Œä¸å¾—ä½¿ç”¨åŸä½œè€…åœ°å€

# å…·ä½“æ–¹æ³•è¯·çœ‹: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions



#  ä»¥è´¦å·    maming0001outlook
#  ä»“åº“åœ°å€  https://github.com/maming0001outlook/xiaopu13853873250 
#  æ–‡ä»¶åœ°å€   https://raw.githubusercontent.com/maming0001/xiaopu13853873250/main/iboxpay.js    ä¸ºä¾‹ 


# ä¸»è¦æ›¿æ¢çš„å­—ç¬¦ğŸ‘‡

# ç¬‘è°±     //jsåå­—
# 0 0-15   //å®šæ—¶ï¼Œå¦‚åŒ—äº¬æ—¶é—´8åˆ°23ç‚¹ï¼Œè®¾ç½®0-15
# XP_refreshTOKEN   //ç¯å¢ƒå˜é‡ä¹‹ä¸€ï¼Œ47è¡Œå¤„è‡ªè¡Œæ·»åŠ å…¶ä»–
# maming0001outlook      //è´¦å·å
# xiaopu13853873250      //ä»“åº“å
# main     //åˆ†æ”¯å
# iboxpay.js  //å­æ–‡ä»¶åœ°å€




name: ç¬‘è°±

on:
  workflow_dispatch:
  schedule:
     - cron: '0 0-15 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        XP_refreshTOKEN: ${{ secrets.XP_refreshTOKEN }}
        
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/maming0001/xiaopu13853873250.git ~/xiaopu13853873250
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.XP_refreshTOKEN
        run: |
          cd ~/xiaopu13853873250
          git checkout main
          npm install
      - name: 'è¿è¡Œ ã€ç¬‘è°±ã€‘'
        if: env.XP_refreshTOKEN
        run: |
          cd ~/xiaopu13853873250
          node iboxpay.js
        env:
          
          PUSH_KEY: ${{ secrets.PUSH_KEY }}
          BARK_PUSH: ${{ secrets.BARK_PUSH }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
          BARK_SOUND: ${{ secrets.BARK_SOUND }}
          DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN }}
          DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET }}
